import os
import threading
import asyncio
from queue import Queue
import requests
import yt_dlp
from pyrogram import Client, filters
from pyrogram.enums import ChatAction
from flask import Flask
from threading import Thread

COOKIES_CONTENT = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
#HttpOnly_.youtube.com	TRUE	/	TRUE	1804358828	__Secure-3PSID	g.a0006QhphkdTJ-Ia1PM4mUD-NBxwcnP9ps6newLjYhsyFV9ReBeLzO5H0e3SJ6BHSvOPdCZp0QACgYKASoSARASFQHGX2MiP6ijiYi14LaE2qdvwk8LqxoVAUF8yKrOZinry2unPTxW-zjiRauF0076
.youtube.com	TRUE	/	FALSE	1802617714	SIDCC	AKEyXzXdNQV-gA1roRom3cP6LemM5zD8fdIqwErMbVvdNkXqRlFq4n5EBSLuxBN8O30_XXwoSg
.youtube.com	TRUE	/	FALSE	1804358828	SID	g.a0006QhphkdTJ-Ia1PM4mUD-NBxwcnP9ps6newLjYhsyFV9ReBeL_puh8Q5AxPbl99fy2maoOQACgYKAUoSARASFQHGX2MiYB-Ndgq07TxjN-FubDHNWxoVAUF8yKocdimrbV3sNUpPFcECWU6y0076
#HttpOnly_.youtube.com	TRUE	/	TRUE	1801334828	__Secure-1PSIDTS	sidts-CjUB7I_69BFegtrBKcY81--WGBDL0eG7S86Lenc9N9qEiAc3ONVcC5bkzjUhggyvxNEBo-3QUBAA
.youtube.com	TRUE	/	TRUE	1771082291	CONSISTENCY	AAsGu9l2Ui23XxEbhTm9zusCQYpzs7-j5FMu6poaLNIqjymOybopVxCU5r9B6mqEwsSS6b2OlRpyANtStInQ7fgXw_2cJ3KU0WCDSVeYcvwvAwgM2a5lIvk6yiY
.youtube.com	TRUE	/	TRUE	1804358828	SAPISID	5hza2jPtQ5ZHRcej/A6quHky7-QWOPla2C
#HttpOnly_.youtube.com	TRUE	/	TRUE	1802617714	__Secure-1PSIDCC	AKEyXzVVbsESDUm_nyVYCEfoDFNawtG7Egxnc3tSk2brUKFhsqhrA4YvVlbCEarsVf6YCM6Uxw
#HttpOnly_.youtube.com	TRUE	/	TRUE	1804358828	SSID	AW3n_HflKZzYTYDkc
.youtube.com	TRUE	/	TRUE	1804358828	__Secure-1PAPISID	5hza2jPtQ5ZHRcej/A6quHky7-QWOPla2C
#HttpOnly_.youtube.com	TRUE	/	TRUE	1804358828	__Secure-1PSID	g.a0006QhphkdTJ-Ia1PM4mUD-NBxwcnP9ps6newLjYhsyFV9ReBeLrzMRTnPg-qHyLA0Q5WCQaAACgYKAY0SARASFQHGX2Mi8HGS_SR3Tdp29KU_rE740BoVAUF8yKqmBOjGDYigIYiQ0NhH7jEL0076
.youtube.com	TRUE	/	TRUE	1804358828	__Secure-3PAPISID	5hza2jPtQ5ZHRcej/A6quHky7-QWOPla2C
#HttpOnly_.youtube.com	TRUE	/	TRUE	1802617714	__Secure-3PSIDCC	AKEyXzU7jQvydevTTVzal_NO4lF6pA3zzEAHeOhBs67X4gRakCiNcvzIO_Y0GlowIP5WK7BwkA
#HttpOnly_.youtube.com	TRUE	/	TRUE	1801334828	__Secure-3PSIDTS	sidts-CjUB7I_69BFegtrBKcY81--WGBDL0eG7S86Lenc9N9qEiAc3ONVcC5bkzjUhggyvxNEBo-3QUBAA
.youtube.com	TRUE	/	FALSE	1804358828	APISID	r-w_2rKmq8q2grSw/AYL2YoQEcwfdQPyxl
#HttpOnly_.youtube.com	TRUE	/	FALSE	1804358828	HSID	ABuD3bG-K6hSxMRNy
#HttpOnly_.youtube.com	TRUE	/	TRUE	1805476979	LOGIN_INFO	AFmmF2swRgIhANHiEXP43InTHaCKdSB2d2Fty63Hzhs9gyeuuyddvoUkAiEAu51ywfEeeNHTOK9lPQFWDjgoz7vBYBqWdbhtA7LhiTk:QUQ3MjNmd3k1WXhQT0d1NXZBZTlDODAySEI3YnRteFJJb0R2dUltYURNMkhWZ3JGbzlaLVc1Rnc0QzFZWlRHd2hDb0Q3N1NzSkIxMjdiR0VweV9qSXd2UWJpWWtVVktNTWZJRHNpMVRtUVpMUTQ0QW9aWmkwd2Qyb0FOS0d4VFZMVmVTM1U1OWVyUTJSbG5yZzc0bXowTFkzdnR6MmxXeUp3
.youtube.com	TRUE	/	TRUE	1805641676	PREF	tz=Africa.Nairobi&f4=4000000
#HttpOnly_.instagram.com	TRUE	/	TRUE	1805649192	datr	M62QaXFk1G23ZJex6f3fX94N
.instagram.com	TRUE	/	TRUE	1802625465	ig_nrcb	1
.instagram.com	TRUE	/	TRUE	1778865719	ds_user_id	78261705240
.instagram.com	TRUE	/	TRUE	1805649719	csrftoken	aJ8xxb21Bz6KbhKJsahSDKoUOixfsZo5
#HttpOnly_.instagram.com	TRUE	/	TRUE	1802625192	ig_did	86C0B207-BA3C-4D9D-94CF-D0DCCAA9E3D5
.instagram.com	TRUE	/	TRUE	1771694514	wd	1504x868
.instagram.com	TRUE	/	TRUE	1805649200	mid	aZCtMwALAAElKs4XQbR_AfMpIJ0E
#HttpOnly_.instagram.com	TRUE	/	TRUE	1802625558	sessionid	78261705240%3AjEjc52yoVd0Tjw%3A8%3AAYj6InobeFg-zte6Xzvps4Hqo9GsPHqMZTJZX81gRw
.instagram.com	TRUE	/	TRUE	1771694514	dpr	1.5
#HttpOnly_.instagram.com	TRUE	/	TRUE	1771176126	rur	"LDC\05478261705240\0541802625729:01feb0f889f9c694e272a10649dd9d1611295652c6e1350703add3cd8d39539bac0aa58b"
"""

COOKIES_TXT_PATH = "cookies.txt"
with open(COOKIES_TXT_PATH, "w") as f:
    f.write(COOKIES_CONTENT)

API_ID = int(os.environ.get("API_ID", "29169428"))
API_HASH = os.environ.get("API_HASH", "55742b16a85aac494c7944568b5507e5")
BOT_TOKEN = os.environ.get("BOT_TOKEN", "8380607635:AAGZiOGbmxwJbberYTJ6HQyvNrasnFAtVFk")

DOWNLOAD_PATH = "downloads"
os.makedirs(DOWNLOAD_PATH, exist_ok=True)

MAX_CONCURRENT_DOWNLOADS = 2
MAX_VIDEO_DURATION = 2400

YDL_OPTS_PIN = {
    "format": "bestvideo+bestaudio/best",
    "outtmpl": os.path.join(DOWNLOAD_PATH, "%(title)s.%(ext)s"),
    "noplaylist": True,
    "quiet": True,
    "cookiefile": COOKIES_TXT_PATH
}

YDL_OPTS_YOUTUBE = {
    "format": "best",
    "outtmpl": os.path.join(DOWNLOAD_PATH, "%(title)s.%(ext)s"),
    "noplaylist": True,
    "quiet": True,
    "cookiefile": COOKIES_TXT_PATH
}

YDL_OPTS_DEFAULT = {
    "format": "best",
    "outtmpl": os.path.join(DOWNLOAD_PATH, "%(title)s.%(ext)s"),
    "noplaylist": True,
    "quiet": True,
    "cookiefile": COOKIES_TXT_PATH
}

SUPPORTED_DOMAINS = [
    "youtube.com", "youtu.be", "facebook.com", "fb.watch", "pin.it",
    "x.com", "tiktok.com", "snapchat.com", "instagram.com"
]

app = Client("video_downloader_bot", api_id=API_ID, api_hash=API_HASH, bot_token=BOT_TOKEN)
flask_app = Flask(__name__)

semaphore = threading.Semaphore(MAX_CONCURRENT_DOWNLOADS)
task_queue = Queue()

@flask_app.route("/")
def home():
    return """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Video Downloader Bot</title>
        <style>
            body {
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                background: linear-gradient(135deg, #1cb5e0 0%, #000851 100%);
                color: white;
                margin: 0;
                padding: 0;
                display: flex;
                justify-content: center;
                align-items: center;
                min-height: 100vh;
            }
            .container {
                background: rgba(255, 255, 255, 0.1);
                backdrop-filter: blur(10px);
                border-radius: 20px;
                padding: 40px;
                max-width: 600px;
                width: 90%;
                box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37);
                border: 1px solid rgba(255, 255, 255, 0.18);
            }
            h1 {
                text-align: center;
                margin-bottom: 30px;
                font-size: 2.5em;
                text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
            }
            .card {
                background: rgba(0, 0, 0, 0.2);
                border-radius: 15px;
                padding: 20px;
                margin-bottom: 20px;
                transition: transform 0.3s ease;
            }
            .card:hover {
                transform: translateY(-5px);
                background: rgba(0, 0, 0, 0.3);
            }
            h3 {
                margin-top: 0;
                color: #00d2ff;
            }
            p {
                line-height: 1.6;
                font-size: 1.1em;
            }
            .footer {
                text-align: center;
                margin-top: 30px;
                font-size: 0.9em;
                opacity: 0.8;
            }
            .status {
                display: inline-block;
                padding: 5px 10px;
                border-radius: 5px;
                background: #2ecc71;
                font-size: 0.8em;
                margin-top: 10px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>📥 Video Downloader</h1>
            <div style="text-align:center; margin-bottom:20px;">
                <span class="status">System Operational</span>
            </div>
            
            <div class="card">
                <h3>🔗 Supported Sites</h3>
                <p>We support downloading from YouTube, TikTok, Instagram, Facebook, Pinterest, X (Twitter), and Snapchat.</p>
            </div>

            <div class="card">
                <h3>⚡ How to Use</h3>
                <p>Simply copy the video link and paste it into the bot chat. The download will start automatically.</p>
            </div>

            <div class="card">
                <h3>⚠️ Limitations</h3>
                <p>To ensure speed for everyone, we currently support videos up to 40 minutes long. 4K videos may be downscaled to 1080p.</p>
            </div>

            <div class="footer">
                <p>Made with ❤️ for easy downloading.</p>
            </div>
        </div>
    </body>
    </html>
    """

def download_thumbnail(url, target_path):
    try:
        resp = requests.get(url, stream=True, timeout=15)
        if resp.status_code == 200:
            with open(target_path, "wb") as f:
                for chunk in resp.iter_content(chunk_size=8192):
                    if chunk:
                        f.write(chunk)
            if os.path.exists(target_path):
                return target_path
    except Exception:
        pass
    return None

def extract_metadata_from_info(info):
    width = info.get("width")
    height = info.get("height")
    duration = info.get("duration")
    if not width or not height:
        formats = info.get("formats") or []
        best = None
        for f in formats:
            if f.get("width") and f.get("height"):
                best = f
                break
        if best:
            if not width:
                width = best.get("width")
            if not height:
                height = best.get("height")
            if not duration:
                dms = best.get("duration_ms")
                duration = info.get("duration") or (dms / 1000 if dms else None)
    return width, height, duration

def download_video(url: str):
    try:
        lowered = url.lower()
        is_pin = "pin.it" in lowered
        is_youtube = "youtube.com" in lowered or "youtu.be" in lowered
        if is_pin:
            ydl_opts = YDL_OPTS_PIN.copy()
        elif is_youtube:
            ydl_opts = YDL_OPTS_YOUTUBE.copy()
        else:
            ydl_opts = YDL_OPTS_DEFAULT.copy()

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)
        width, height, duration = extract_metadata_from_info(info)
        if duration and duration > MAX_VIDEO_DURATION:
            return None
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info_dl = ydl.extract_info(url, download=True)
            filename = ydl.prepare_filename(info_dl)
        title = info_dl.get("title") or ""
        desc = info_dl.get("description") or ""
        thumb = None
        thumb_url = info_dl.get("thumbnail")
        if thumb_url:
            thumb_path = os.path.splitext(filename)[0] + ".jpg"
            thumb = download_thumbnail(thumb_url, thumb_path)
        return title, desc, filename, width, height, duration, thumb
    except Exception as e:
        return f"ERROR: {str(e)}"

def process_download_sync(client, message, url):
    try:
        client.send_chat_action(message.chat.id, ChatAction.TYPING)
        result = download_video(url)
        if result is None:
            try:
                message.reply_text("Masoo dajin kari video ka dheer 40 minute 👍")
            except Exception:
                pass
        elif isinstance(result, str) and result.startswith("ERROR"):
            try:
                message.reply_text(f"❌ Cilad ayaa dhacday:\n`{result}`")
            except Exception:
                pass
        else:
            title, desc, file_path, width, height, duration, thumb = result
            try:
                client.send_chat_action(message.chat.id, ChatAction.UPLOAD_VIDEO)
            except Exception:
                pass
            try:
                me = client.get_me()
                bot_username = f"@{me.username}" if getattr(me, "username", None) else "SooDajiye Bot"
            except Exception:
                bot_username = "SooDajiye Bot"

            caption = title if title else (desc[:100] if desc else bot_username)
            if len(caption) > 1024:
                caption = caption[:1021] + "..."

            send_kwargs = {"chat_id": message.chat.id, "video": file_path, "caption": caption, "supports_streaming": True}
            if width: send_kwargs["width"] = int(width)
            if height: send_kwargs["height"] = int(height)
            if duration: send_kwargs["duration"] = int(float(duration))
            if thumb and os.path.exists(thumb): send_kwargs["thumb"] = thumb

            try:
                client.send_video(**send_kwargs)
            except Exception as e:
                message.reply_text(f"Video waa la soo dejiyay laakiin Telegram ayaa diiday inuu qaado: {str(e)}")

            for fpath in [file_path, thumb]:
                if fpath and os.path.exists(fpath):
                    os.remove(fpath)
    finally:
        semaphore.release()
        if not task_queue.empty():
            next_item = task_queue.get()
            t_client, t_message, t_url = next_item
            semaphore.acquire()
            threading.Thread(target=threaded_worker, args=(t_client, t_message, t_url), daemon=True).start()

def threaded_worker(client, message, url):
    try:
        process_download_sync(client, message, url)
    except Exception as e:
        print(f"[THREAD ERROR] {e}")

@app.on_message(filters.private & filters.command("start"))
def start(client, message):
    message.reply_text("👋 Salaam Iisoodir link si aan kuugu soo dajiyo video-ga.")

@app.on_message(filters.private & filters.text)
def handle_link(client, message):
    url = message.text.strip()
    if not any(domain in url.lower() for domain in SUPPORTED_DOMAINS):
        message.reply_text("kaliya Soodir link video saxa 👍")
        return

    if semaphore.acquire(blocking=False):
        threading.Thread(target=threaded_worker, args=(client, message, url), daemon=True).start()
    else:
        task_queue.put((client, message, url))
        message.reply_text("Saf ayuu ku jiraa, fadlan sug...")

def run_flask():
    port = int(os.environ.get("PORT", 8080))
    flask_app.run(host="0.0.0.0", port=port)

if __name__ == "__main__":
    try:
        loop = asyncio.get_event_loop()
    except RuntimeError:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        
    Thread(target=run_flask, daemon=True).start()
    app.run()
